STOCKCODE = ['AAPL', 'MSFT', 'BAC', 'AMZN', 'IBM', 'GOOG', 'MO', 'DAL', 
             'AA', 'AXP', 'DD', 'BABA', 'ABT', 'UA', 'AMAT', 'AMGN', 
             'AAL', 'AIG', 'ALL', 'ADBE', 'GOOGL', 'ACN', 'ABBV', 'MT', 
             'META', 'NVDA', 'ADP', 'AKAM', 'NLY',
             'ADSK', 'ADM', 'WBA', 'LUV', 'ACAD', 'PANW', 'AMD', 
             'KO', 'AVGO', 'EA', 'DB', 'INTC', 'AEM', 'APD', 
             'AMBA', 'NVS', 'ANF', 'LULU', 'ARRY', 'AGNC', 'JBLU', 
             'NFLX', 'ORLY', 'FOLD', 'AZO', 'AN', 'AZN', 'WMT', 'BUD', 
             'PYPL', 'BDX', 'AB', 'CSCO', 'AFL', 'ADI', 'ACIW', 
             'AMP', 'AMTD', 'AEO', 'AWK', 'NVO', 'ALTR', 'TSLA', 'PAA', 'ARCC',
             'AAP', 'NAT', 'FNMA', 'MRK', 'AGIO', 'AEE', 'UBS', 'AVXL',
             'COST', 'PEP', 'TMUS', 'LIN', 'TXN', 'ANET', 'SYK',
             'PGR', 'SCHW', 'PLTR', 'TWLO', 'NOW', 'SQ', 'DOCU', 'HUBS', 'RNG', 'CRWD',
             'ZS', 'ROKU']